models/contact.py
import email
from operator import imod
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(200), nullable=False)
    phone = db.Column(db.String(10), nullable=False)

    def __init__(self, fullname, email, phone):
        self.fullname=fullname
        self.email=email
        self.phone=phone

app.py
import imp
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key='secret key'
app.config['SQLALCHEMY_DATABASE_URI']=DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, redirect, render_template, request, url_for, flash
from models.contact import Contact
from utils.db import db

contacts=Blueprint('contacts',__name__)

#Mostrar interfaz con contactos y formulario
@contacts.route('/')
def home():
    contactslist=Contact.query.all()
    return render_template('index.html', contacts=contactslist)

#Agregar contacto
@contacts.route('/new', methods=['POST'])
def add_contact():
    fullname=request.form['fullname']
    email=request.form['email']
    phone=request.form['phone']

    new_contact=Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()
    flash('Contact added successfully')
    return redirect(url_for('contacts.home'))

@contacts.route('/update/<id>', methods=['POST', 'GET'])
def update_contact(id):
    contactupd=Contact.query.get(id)
    if(request.method=='POST'):
        contactupd.fullname=request.form['fullname']
        contactupd.email=request.form['email']
        contactupd.phone=request.form['phone']
        db.session.commit()
        flash('Contact updated successfully')
        return redirect(url_for('contacts.home'))
    else:
        return render_template('update.html', contupd=contactupd)

@contacts.route('/delete/<id>')
def delete_contact(id):
    contactdel=Contact.query.get(id)
    db.session.delete(contactdel)
    db.session.commit()
    flash('Contact deleted successfully')
    return redirect(url_for('contacts.home'))

@contacts.route('/about')
def about():
    return render_template('about.html')

templates/about.html
{% extends 'layout.html' %}
{% block content %}
<div class="text-light">
    <h1>About</h1>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}
{% block content %}
    {% include('partials/_messages.html')%}

<div class="row">
    <div class="col-md-5">
        {% include('partials/_contactForm.html') %}
    </div>
    <div class="col-md-7">
            <h3 style="color: white;">Contact List</h3>
            {% for contact in contacts %}
            <div class="card mb-1 text-white bg-dark">
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h5>{{contact.fullname}}</h5>
                        <div>
                            <a class="btn btn-warning btn-sm ronded-0" href="{{url_for('contacts.update_contact', id=contact.id)}}">Update</a>
                            <a class="btn btn-danger btn-sm ronded-0" href="{{url_for('contacts.delete_contact', id=contact.id)}}">Delete</a>
                        </div>
                    </div>
                    <p>{{contact.email}}</p>
                    <p>{{contact.phone}}</p>
                    
                </div>
            </div>
            {% endfor %}
    </div>

</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Flask With SQL-Alchemy CRUD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    {% include('partials/_navbar.html')%}
    <!--Content es el nombre del bloque, este nombre puede ser cualquiera-->
    <div class="container p-2">
        {% block content %}
        {% endblock %}
    </div>


</body>
</html>

templates/partials/_contactForm.html
<h3 style="color: white;">Add Contact</h3>
    <form action="/new" method="POST" class="card bg-dark text-light">
        
        
        <div class="card-body p-4">
            <div class="mb-3">
                <label for="fullname">Write your fullname</label>
                <input class="form-control rounded-0 bg-dark text-white" required type="text" maxlength="200" name="fullname" placeholder="Write your fullname">
            </div>
            <div class="mb-3">
                <label for="email">Write your email</label>
                <input class="form-control rounded-0 bg-dark text-white" required type="email" maxlength="200" name="email" placeholder="Write your email">
            </div>
            <div class="mb-3">
                <label for="phone">Write your phone number</label>
                <input class="form-control rounded-0 bg-dark text-white" required type="text" maxlength="10" minlength="10" name="phone" placeholder="Write your phone number">
            </div>
            <button class="btn btn-primary" type="submit">
                Save
            </button>
        </div>
    </form>

templates/partials/_messages.html
{% with messages= get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <script>
                Swal.fire(
                    'Correcto',
                    '{{message}}',
                    'success'
                )
            </script>
        {% endfor %}
    {% endif %}
{% endwith%}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Flask SQL-Alchemy CRUD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
            
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/update.html
{% extends 'layout.html' %}
{% block content %}
<h1 style="color: white;">Update contact</h1>
<form action="/update/{{contupd.id}}" method="POST" class="card bg-dark text-light">
    <div class="card-body p-4">
        <div class="mb-3">
            <label for="fullname">Write your fullname</label>
            <input class="form-control rounded-0 bg-dark text-white" required type="text" maxlength="200" name="fullname" placeholder="Write your fullname" value="{{contupd.fullname}}">
        </div>
        <div class="mb-3">
            <label for="email">Write your email</label>
            <input class="form-control rounded-0 bg-dark text-white" required type="email" maxlength="200" name="email" placeholder="Write your email" value="{{contupd.email}}">
        </div>
        <div class="mb-3">
            <label for="phone">Write your phone number</label>
            <input class="form-control rounded-0 bg-dark text-white" required type="text" maxlength="10" minlength="10" name="phone" placeholder="Write your phone number" value="{{contupd.phone}}">
        </div>
        <button class="btn btn-primary" type="submit">
            Save
        </button>
    </div>
</form>
{% endblock %}